# Generated by Django 5.0.1 on 2024-01-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pays')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du type de propriété')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la ville')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appart.country', verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'arrondissement")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appart.city', verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la rue')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appart.district', verbose_name='Arrondissement')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Nombre de chambres')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Nombre de salles de bains')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du loyer')),
                ('available_for_rent', models.BooleanField(default=True, verbose_name='Disponible à la location')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appart.city', verbose_name='Ville')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appart.country', verbose_name='Pays')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appart.district', verbose_name='Arrondissement')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appart.propertytype', verbose_name='Type de propriété')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appart.street', verbose_name='Rue')),
            ],
        ),
    ]
