# Generated by Django 5.0.1 on 2024-01-23 16:12

import appart.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='appartement_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='appartement_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='appartement_photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='appartement_photos/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='appartement_photos/')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='appartement_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='appartement_videos/', validators=[appart.models.validate_video])),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appart.propertytype', verbose_name='Type de propriété')),
            ],
        ),
    ]
