# Generated by Django 5.0.1 on 2024-01-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_appartement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appartement',
            new_name='MediaProperty',
        ),
    ]
