# Generated by Django 5.0.1 on 2024-01-24 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0004_remove_mediaproperty_video_alter_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaproperty',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='mediaproperty',
            name='property_type',
        ),
        migrations.AddField(
            model_name='mediaproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appart.property', verbose_name='Type de propriété'),
        ),
    ]
