# Generated by Django 5.0.1 on 2024-01-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0005_remove_mediaproperty_photo6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la propriéte'),
        ),
    ]
