# Generated by Django 5.0.1 on 2024-01-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0006_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appart.propertytype', verbose_name='Type de propriété'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200, verbose_name="Nom de l'arrondissement")),
                ('address', models.CharField(max_length=255, verbose_name='Addresse')),
                ('street', models.CharField(max_length=100, verbose_name='Nom de la rue')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appart.city', verbose_name='Ville')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appart.country', verbose_name='Pays')),
            ],
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
