# Generated by Django 5.0.1 on 2024-01-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0008_remove_property_address_address_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Appartement'), (2, 'Duplex'), (3, 'Immeuble')], null=True, verbose_name='Type de propriété'),
        ),
    ]
