# Generated by Django 5.0.1 on 2024-02-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0012_remove_address_city_remove_address_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaProperty',
        ),
    ]
