# Generated by Django 5.0.1 on 2024-01-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0007_remove_street_district_remove_property_district_and_more'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartementdetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.property'),
        ),
        migrations.AlterField(
            model_name='duplexdetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.property'),
        ),
        migrations.AlterField(
            model_name='immeubledetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.property'),
        ),
        migrations.AddField(
            model_name='appartementdetails',
            name='superficie',
            field=models.IntegerField(default='200'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
