# Generated by Django 5.0.1 on 2024-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_country_property_propertytype_city_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyType',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Appartement'), (2, 'Duplex'), (3, 'Immeuble'), (4, 'Studio'), (5, 'Chambre Moderne')], null=True, verbose_name='Type de Propriéte'),
        ),
    ]
