# Generated by Django 5.0.1 on 2024-01-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0006_remove_address_city_remove_address_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pays')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la propriéte')),
                ('property_type', models.IntegerField(blank=True, choices=[(1, 'Appartement'), (2, 'Duplex'), (3, 'Immeuble'), (4, 'Studio'), (5, 'Chambre Moderne')], null=True, verbose_name='Type de Propriéte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du loyer')),
                ('available_for_rent', models.BooleanField(default=True, verbose_name='Disponible à la location')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la ville')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.country', verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='ImmeubleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_level', models.IntegerField()),
                ('count_appartement', models.IntegerField()),
                ('count_studio', models.IntegerField()),
                ('count_bedroom', models.IntegerField()),
                ('superficie', models.IntegerField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='DuplexDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('superficie', models.IntegerField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='AppartementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('superficie', models.IntegerField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200, verbose_name="Nom de l'arrondissement")),
                ('address', models.CharField(max_length=255, verbose_name='Addresse')),
                ('street', models.CharField(max_length=100, verbose_name='Nom de la rue')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.city', verbose_name='Ville')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.country', verbose_name='Pays')),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Type de propriété')),
            ],
        ),
    ]
