# Generated by Django 5.0.1 on 2024-01-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0011_initial'),
        ('property', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AlterField(
            model_name='immeubledetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.property'),
        ),
        migrations.AlterField(
            model_name='duplexdetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.property'),
        ),
        migrations.AlterField(
            model_name='appartementdetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.property'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
