# Generated by Django 5.0.1 on 2024-02-03 15:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_country_property_propertytype_city_mediaproperty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RenameField(
            model_name='appartementdetails',
            old_name='bathroom',
            new_name='count_bathroom',
        ),
        migrations.RenameField(
            model_name='appartementdetails',
            old_name='bedroom',
            new_name='count_bedroom',
        ),
        migrations.RenameField(
            model_name='duplexdetails',
            old_name='bathroom',
            new_name='count_bathroom',
        ),
        migrations.RenameField(
            model_name='duplexdetails',
            old_name='bedroom',
            new_name='count_bedroom',
        ),
        migrations.RemoveField(
            model_name='mediaproperty',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='mediaproperty',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='mediaproperty',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='mediaproperty',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='mediaproperty',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_for_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='name',
        ),
        migrations.AddField(
            model_name='appartementdetails',
            name='count_saloon',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duplexdetails',
            name='count_saloon',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaproperty',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='property_photo/'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Appartement'), (2, 'Duplex'), (3, 'Immeuble'), (4, 'Hotel'), (5, 'Studio')], default=1, verbose_name='Nom du type de propriété'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaproperty',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Type de propriété'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.propertytype', verbose_name='Type de propriété'),
        ),
        migrations.AddField(
            model_name='description',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
