# Generated by Django 5.0.1 on 2024-02-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_description_delete_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartementdetails',
            name='count_bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appartementdetails',
            name='count_bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appartementdetails',
            name='count_saloon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appartementdetails',
            name='superficie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplexdetails',
            name='count_bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplexdetails',
            name='count_bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplexdetails',
            name='count_saloon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplexdetails',
            name='superficie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubledetails',
            name='count_appartement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubledetails',
            name='count_bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubledetails',
            name='count_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubledetails',
            name='count_studio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immeubledetails',
            name='superficie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
