# Generated by Django 5.0.1 on 2024-02-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_appartementdetails_count_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartementdetails',
            name='count_saloon',
        ),
        migrations.RemoveField(
            model_name='duplexdetails',
            name='count_saloon',
        ),
    ]
